
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import SocketProvider from "./context/socketProvider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "ChatWave - An application to interact with others",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="shortcut icon" href="favicon.ico" sizes="32x32" type="image/x-icon" />
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SocketProvider>   
        {children}
        </SocketProvider>
      </body>
    </html>
  );
}
